version: "3.9"

services:
  fcm_notifier:
    image: htetlinmaung/fcm_notifier
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION=mongodb://hlm:Password@mongo:27017/fcmschdules?authSource=admin
      - FIREBASE_FCM_URL=https://fcm.googleapis.com/fcm/send
      - FIREBASE_FCM_AUTH="key=AAAAbqDfgxU:APA91bFyK7L-58Gz9IJfMY_5BIZY5KTDRHKLHz3di5oh_Jab0G730E0OmP3tZgDobMLg82jFWKoVDQtKprqEm8fgN-dh4ZnBG_vJXrQh9tVkx2WmSvuo9oEuDCbLGxBilBLgvKhYVUqw"
    # deploy:
    #   replicas: 1
  mongo:
    image: mongo
    restart: always
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hlm
      MONGO_INITDB_ROOT_PASSWORD: Password
    volumes:
      - mongodb:/data/db
    # deploy:
    #   replicas: 1

volumes:
  mongodb:
